### PR TITLE
projects: add pre-built 9082xs kernel module to S905

### PR DESCRIPTION
**Pull request by dtechsrv**
There is no public source code for this wifi chip, so the pre-built module was added, which was also found in v8.2 by @kszaq.

### CODE REVIEW

**Comment by dtechsrv** [comment]
@matiasw
Please test this snapshot image: http://libreelec.dtech.hu/snapshots/20220911/

**Comment by matiasw** [comment]
I tried updating from 9.2.5 by putting the tar file in the Update directory using Samba. After rebooting, however, I got "No Signal" on my TV. So, I tried writing a new SD card entirely using the .gz file. This, also, resulted in "No Signal". In other words, neither method yielded a booting configuration.
So, unfortunately, I can not verify the working of this image one way or the other. 

I appreciate the effort you're going through to get this working.

**Comment by dtechsrv** [comment]
Interesting, you will have some other problem here during boot.
I also prepared the image for KI Pro and tried to load `9082xs` module manually, of course without the affected wifi chip.

I didn't get any errors on the module, it just said:
```[  238.411449@2] TLL901X: module init start
[  238.411453@2] TLL901X: tll9082es v1.2.0_0046.20160328
[  238.411477@2] aml_wifi wifi.33: [extern_wifi_set_enable] WIFI  Disable! 240
[  238.919413@2] aml_wifi wifi.33: [extern_wifi_set_enable] WIFI  Enable! 240
[  239.429331@2] sdio_reset_comm():
[  239.457501@0] sdio: queuing unknown CIS tuple 0x80 (2 bytes)
[  239.462867@0] sdio: queuing unknown CIS tuple 0x80 (7 bytes)
[  239.465402@0] sdio: queuing unknown CIS tuple 0x80 (3 bytes)
[  239.559519@0] sdio: clk 200000000 SDR mode tuning start
[  239.559682@0] sdio: rx_tuning_result[0] = 10
[  239.559834@0] sdio: rx_tuning_result[1] = 10
[  239.560001@0] sdio: rx_tuning_result[3] = 10
[  239.560150@0] sdio: rx_tuning_result[4] = 10
[  239.560153@0] sdio: best_win_start =3, best_win_size =4
[  239.560156@0] sdio: sd_emmc_regs->gclock=0x1000245,sd_emmc_regs->gadjust=0x2000
[  239.560160@0] sdio: gclock =0x1000245, gdelay=0x0, gadjust=0x2000
[  239.560162@0] [sdio_reinit] finish
[  239.560369@0] TLL901X: module init ret=0
```
So in theory it could work.

**Comment by matiasw** [comment]
Any ideas on how to debug?

**Comment by dtechsrv** [comment]
Actually, it would be best if you had a TTL signal level UART adapter.
If you don't have one, try what I wrote as an answer on the forum first.

**Comment by matiasw** [comment]
I don't have a TTL UART adapter. 

I am just reverting to the working version, for now.

Thanks for trying to help. I made a small donation to the project so that your time spent on this is not a complete loss.

**Comment by dtechsrv** [comment]
Thank you for your sponsorship.

There is one question that bothers me:
If you write again v​​9.2.8.5 on the same card, does it boot again or not? If not, then something else is going on in the background.

Anyway, I tried to search for it and in several forums I found that K12 would be the RESET button on the PCB, but most of the time it was not even soldered into the box:
M8S_Pro_PLUS

But, if it is still soldered in, it can be found here:
https://www.youtube.com/watch?v=N27pAxtcDSg&t=274s

**Comment by matiasw** [comment]
Yes, if I write 9.2.8.5 (sorry for mistakenly calling it 9.2.5 before; this is what I meant) on the card, it boots. So, there should be something in the diff to the snapshot besides the wifi module addition..!

**Comment by matiasw** [comment]
Ok, so I tried blacklisting the wifi module by following [this guide](https://wiki.libreelec.tv/how-to/blacklist-kernel-module).

I had to create the `.config` directory and `./modprobe.d/` under it as they did not exist. I added `blacklist 9082xs` into `blacklist.conf` in this directory, but I don't know if this is even a valid approach to stopping the 9082xs module from being loaded - is it loaded by modprobe?

In any case, even with this configuration in place, the 9.2.8.6 version did not boot.

**Comment by dtechsrv** [comment]
By blacklisting this module, we are working against ourselves, since this module is supposed to start your wifi chip. However, it looks like the module itself is causing the boot problem, but we could only be sure of this if a kernel panic could be displayed on UART.

**Comment by matiasw** [comment]
I decided to try again, and got the 9.2.8.6 image to boot into the part where it resizes the file system and reboot, but it got stuck in the following boot screen with "LibreELEC (dtech): 9.2.8.6" in the upper left corner and the LibreELEC logo in the middle.

**Comment by matiasw** [comment]
I am still trying to get this to work, so please do not close the issue.

I tried the new snapshot in http://libreelec.dtech.hu/snapshots/20230108-ee6102d/LibreELEC-Generic_S905.arm-9.2.8.7.img.gz , but did not get it to boot, not even to the "Resizing filesystem" screen.

**Comment by dtechsrv** [comment]
The image you are trying now does not contain the relevant wifi driver, and I have already deleted the previous snapshot image.
Because I don't have such a box in which this wifi chip is integrated, and since there is no published source for this wireless module, unfortunately I can't do anything more. But, if you have any suggestion, I would welcome it.

**Comment by matiasw** [comment]
Well, how about a new snapshot with the wifi driver for me to try?

**Comment by dtechsrv** [comment]
I think you should first find out why the image doesn't boot at all, wifi is of secondary importance until then.

**Comment by dtechsrv** [comment]
http://libreelec.dtech.hu/snapshots/20230112_9082xs-wifi_7c1f4df/

It also includes the wifi driver. Don't forget to replace the correct dtb.

**Comment by matiasw** [comment]
Ok, so I downloaded the snapshot from [the link](http://libreelec.dtech.hu/snapshots/20230112_9082xs-wifi_7c1f4df/) and wrote it to the micro-SD card with LibreELEC-AML.USB-SD.Creator.Win32. I then inserted the card in my Mecool box and powered it on, whereupon it booted from internal. So, I used [Reboot to LibreELEC app](https://play.google.com/store/apps/details?id=me.thomastv.rebootupdate) to boot from SD. It resized the file system, then restarted, and, once again, got stuck in the LibreELEC logo splash screen, with "LibreELEC (dtech): 9.2.8.7" in the upper left corner. 

I guess to further analyze the situation, I would need something like the UART debugger we discussed earlier?

**Comment by dtechsrv** [comment]
Yes, you got it right. You should try this in the same way:
http://libreelec.dtech.hu/snapshots/20230108_master_ee6102d/LibreELEC-Generic_S905.arm-9.2.8.7.img.gz

If your box boots with this image, then there is really nothing to do, because the error is caused by the external kernel module itself. Since there is no source code published, I can't do anything with it, unfortunately.

**Comment by matiasw** [comment]
I was adviced on `#libreelec` to use the dtb specific to the version, and not carry one over from a previous install. So, from [this list](https://www.reddit.com/r/Emuelec/comments/hxrggg/dtb_list_for_your_device/) I got the dtb name, and took the `gxl_p212_2g.dtb` to the root and renamed it `dtb.img`. This made the wifi-less version boot, but not the version with wifi, so I suppose wifi is a lost hope. However, I've run a wire anyway, so I will adopt the `9.2.8.7` without wifi as my daily LibreELEC. Thanks!

**Pull request closed without merging**
