### PR TITLE
Update Realtek RTL8152 USB NIC driver from v1.0.0 (2013/05/03) to v1.04.0 (2014/01/15)

### PR DESCRIPTION
**Pull request by dtechsrv**

### CODE REVIEW

**Comment by dtechsrv** [comment]
@MyKeySoftMK

Please try this snapshot image on your box with RTL8153 USB 3.0 Ethernet:
http://libreelec.dtech.hu/snapshots/20230207_rtl8153-aml-3.10_59800cc/

**Comment by MyKeySoftMK** [comment]
> @MyKeySoftMK
> 
> Please try this snapshot image on your box with RTL8153 USB 3.0 Ethernet: http://libreelec.dtech.hu/snapshots/20230207_rtl8153-aml-3.10_59800cc/

Thank for the link. I have try it - but the USB LAN is not working. Do you need some more information?

**Comment by dtechsrv** [comment]
First, I need a `dmesg` and an `lsmod` output.

**Comment by MyKeySoftMK** [comment]
> First, I need a `dmesg` and an `lsmod` output.

Here are the results
[dmesq.log](https://github.com/dtechsrv/LibreELEC-AML/files/10683326/dmesq.log)
[lsmod.log](https://github.com/dtechsrv/LibreELEC-AML/files/10683327/lsmod.log)

**Comment by dtechsrv** [comment]
According to the signs, the driver is loading and the module is fine. I only see one error message, but I don't know which interface it belongs to.

```
[    6.679649@3] usb 2-1.1: New USB device found, idVendor=0bda, idProduct=8153
[    6.679654@3] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    6.679658@3] usb 2-1.1: Product: USB 10/100/1000 LAN
[    6.679661@3] usb 2-1.1: Manufacturer: Realtek
[    6.679665@3] usb 2-1.1: SerialNumber: 00E04C6803E3
...
[   33.956692@0] r8152 2-1.1:1.0 eth1: v1.04.0 (2014/01/15)
[   33.966391@0] usbcore: registered new interface driver r8152
[   33.991277@1] usbcore: registered new interface driver cdc_ether
[   34.651560@0] eth0: device MAC address 00:01:23:cd:ee:af
[   34.651786@0] stmmac_open: Cannot attach to PHY (error: -19)
[   34.659106@3] IPv6: ADDRCONF(NETDEV_UP): eth1: link is not ready
...
[   37.635423@0] IPv6: ADDRCONF(NETDEV_CHANGE): eth1: link becomes ready
```

Can you send an `ifconfig` output as well?

**Comment by MyKeySoftMK** [comment]
Here is the output - only the WLAN is connected

`
LibreELEC:~ # ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

wlan0     Link encap:Ethernet  HWaddr 6C:FA:A7:DD:01:32
          inet addr:192.168.2.61  Bcast:192.168.2.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:8690 errors:0 dropped:7749 overruns:0 frame:0
          TX packets:545 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:477058 (465.8 KiB)  TX bytes:182737 (178.4 KiB)

`

**Comment by dtechsrv** [comment]
Did the integrated interface (eth0) work before? I need a clean `dmesg` and `ifconfig` under the lastest stable image (v9.2.8.7).

**Comment by dtechsrv** [comment]
Wait a minute, your box is actually a stick without Ethernet. In this case, DTB is not suitable either.

**Comment by MyKeySoftMK** [comment]
My last working Version was "OpenELEC 5.95.5.2"

**Comment by MyKeySoftMK** [comment]
> Wait a minute, your box is actually a stick without Ethernet. In this case, DTB is not suitable either.

Yes - I must put in the USB-LAN to use it

**Comment by MyKeySoftMK** [comment]
Sorry - I found out the problem: the OTG-Adapter was from wrong type - they didn´t give the power to the LAN-USB. Now I change them and it works fine.

Thank you very much. You can close the Issue

**Comment by dtechsrv** [comment]
Can I get a `dmesg` and an `ifconfig` under the working system? If everything is correct, the updated driver will be included in the kernel from the next version.

**Comment by MyKeySoftMK** [comment]
Yes - no problem - here are the files for you

[dmesg.log](https://github.com/dtechsrv/LibreELEC-AML/files/10685371/dmesg.log)
[ifconfig.log](https://github.com/dtechsrv/LibreELEC-AML/files/10685372/ifconfig.log)

**Pull request merged**
